import {
  PROMPTFOO_DATASET_ITEM_ID_VAR,
  PROMPTFOO_DATASET_ITEM_VERSION_VAR,
  PROMPTFOO_EXPECTED_OUTPUT_VAR,
  PROMPTFOO_REPORT_HTML_FORMAT,
  PROMPTFOO_REPORT_JSON_FORMAT,
} from "@langfuse/shared";

export const PROMPTFOO_LANGFUSE_PROMPT_ID_PREFIX = "Langfuse prompt id:";

export {
  PROMPTFOO_DATASET_ITEM_ID_VAR,
  PROMPTFOO_DATASET_ITEM_VERSION_VAR,
  PROMPTFOO_EXPECTED_OUTPUT_VAR,
  PROMPTFOO_REPORT_HTML_FORMAT,
  PROMPTFOO_REPORT_JSON_FORMAT,
};
export const PROMPTFOO_VERSION = "0.121.8";
